image: registry.gitlab.com/wendbv/wend-internal/docker-base-image:latest

stages:
  - build
  - deploy/production
  - deploy/staging

build:production:
  when: manual
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build
  environment:
    name: production
  script:
    - yarn install --pure-lockfile --no-cache
    - yarn build

deploy:production:
  when: manual
  only:
    - master
  stage: deploy/production
  dependencies:
    - build:production
  environment:
    name: production
  script:
    - aws s3 sync build/ s3://$PRODUCTION__S3_BUCKET/$PRODUCTION__S3_PATH --delete --acl public-read

deploy:staging:
  when: manual
  stage: deploy/staging
  dependencies:
    - build:production
  environment:
    name: production
  script:
    - aws s3 sync build/ s3://$PRODUCTION__S3_BUCKET/$STAGING__S3_PATH --delete --acl public-read
